### ISSUE TITLE
3D Data on Prototype

### ISSUE THREAD

**Issue by djrobby** [zhivko/PipeCutter#1]
Do you plan on sharing the 3D model data for others to create this prototype and test your code base as well? Are you looking for additional help with the mechanical design?

**Comment by zhivko** [comment]
This mechanism is very simple - it consist off one big rotating wheel that is turning via timing belt with motor.
I currently don't need help around mechanical design - however I am looking for ideas how to eliminate motor positioning of pipe into the center point of pipe rotation.

You plan to reproduce this?
